#!/bin/bash

# NVDA Remote Go Configuration Setup Script
# This script interactively creates a .env file with your NVDA Remote configuration

echo "======================================"
echo "NVDA Remote Go Configuration Setup"
echo "======================================"
echo ""

# Check if .env already exists
if [ -f .env ]; then
    echo "Warning: .env file already exists!"
    read -p "Do you want to overwrite it? (y/N): " overwrite
    if [[ ! $overwrite =~ ^[Yy]$ ]]; then
        echo "Setup cancelled. Existing .env file kept."
        exit 0
    fi
    echo ""
fi

# Prompt for NVDA_REMOTE_KEY (required)
echo "Enter your NVDA Remote key (required):"
read -r nvda_key
while [ -z "$nvda_key" ]; do
    echo "Error: NVDA Remote key is required!"
    echo "Enter your NVDA Remote key:"
    read -r nvda_key
done

# Prompt for NVDA_REMOTE_HOST (optional)
echo ""
echo "Enter NVDA Remote server host (press Enter for default: nvdaremote.ru):"
read -r nvda_host
if [ -z "$nvda_host" ]; then
    nvda_host="nvdaremote.ru"
fi

# Prompt for NVDA_REMOTE_PORT (optional)
echo ""
echo "Enter NVDA Remote server port (press Enter for default: 6837):"
read -r nvda_port
if [ -z "$nvda_port" ]; then
    nvda_port="6837"
fi

# Create .env file
cat > .env << EOF
# NVDA Remote Configuration
# Generated by setup.sh on $(date)

# Your NVDA Remote key (required)
NVDA_REMOTE_KEY=$nvda_key

# NVDA Remote server host (optional, defaults to nvdaremote.ru)
NVDA_REMOTE_HOST=$nvda_host

# NVDA Remote server port (optional, defaults to 6837)
NVDA_REMOTE_PORT=$nvda_port
EOF

echo ""
echo "======================================"
echo "Configuration saved to .env"
echo "======================================"
echo ""
echo "Configuration summary:"
echo "  NVDA_REMOTE_KEY: $nvda_key"
echo "  NVDA_REMOTE_HOST: $nvda_host"
echo "  NVDA_REMOTE_PORT: $nvda_port"
echo ""
echo "You can now run any example application!"
echo "For example: cd examples/vgui/simple_form && go run ."
echo ""
